### ISSUE TITLE
Chatham 2-1 2020 Duplicate

### ISSUE THREAD

**Issue by IJBG** [nc-minibbs/mbbs#140] opened 2024-12-05 21:29 UTC
Not sure what happened in 2020 with these two routes for rt2 -
https://ebird.org/checklist/S69645921
https://ebird.org/checklist/S69224607

Did Norm skip stop 1 on the 17 May visit, and Patsy went back to fill in on 25 May?

I think Norm's visit should be excluded (it's a route summary anyway), but should the comment on Patsy's 2-1 be changed to reflect that Norm ran the route? Maybe add them both as observers?

**Comment by IJBG** [comment] 2024-12-05 21:46
Another issue, chatham 13 2001 is still giving the Mallard warning, despite that I'm pretty sure we already resolved that:
`WARN [2024-12-05 16:35:26] cthm-13-NA, 2011, Mallard: had more than 1 submission`

**Comment by ahhurlbert** [comment] 2024-12-06 14:06
We determined that the data for Chatham Rte 2 by Patsy was mislabeled and was actually a duplicate of Patsy's Rte 1. This has been removed.

**Closed by ahhurlbert** 2024-12-06 14:06 UTC
